<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>CryptoExchangeGT.Cifrador</RootNamespace>
    <AssemblyName>cifrador</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CryptoExchangeGT.Infrastructure\CryptoExchangeGT.Infrastructure.csproj" />
  </ItemGroup>

</Project>
