// <auto-generated />
using System;
using CryptoExchangeGT.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoExchangeGT.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CryptoExchangeGT.Domain.Entities.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Compensada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DireccionDestino")
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashBlockchain")
                        .HasMaxLength(66)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoCripto")
                        .HasColumnType("decimal(28,18)");

                    b.Property<decimal>("MontoGTQ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoFallo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TasaCambioUsada")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("HashBlockchain");

                    b.HasIndex("ReferenciaExterna")
                        .IsUnique()
                        .HasFilter("\"ReferenciaExterna\" IS NOT NULL");

                    b.HasIndex("UsuarioId", "FechaCreacion");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("CryptoExchangeGT.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoGTQ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CryptoExchangeGT.Domain.Entities.WalletCustodia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionPublica")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUltimaSincronizacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GasPatrocinado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlavePrivadaCifrada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoCriptoCacheado")
                        .HasColumnType("decimal(28,18)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DireccionPublica")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("WalletsCustodia");
                });

            modelBuilder.Entity("CryptoExchangeGT.Domain.Entities.Transaccion", b =>
                {
                    b.HasOne("CryptoExchangeGT.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoExchangeGT.Domain.Entities.WalletCustodia", b =>
                {
                    b.HasOne("CryptoExchangeGT.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("CryptoExchangeGT.Domain.Entities.WalletCustodia", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
